### ISSUE TITLE
[Bug] Game crashed on world generation {1.20.1}

### ISSUE THREAD

**Issue by SupGamerNL** [Stardust-Labs-MC/Terralith#42]
### What Minecraft version(s) does this apply to?

1.20

### Project version

v2.4.3

### Mod or datapack version?

Mod (Forge)

### Describe the bug

While creating a world and generating it, my game crashes.

After the game crashed both the latest.log and crash...-client.txt state the following:
Caused by: java.lang.IllegalStateException: Feature order cycle found, involved sources: 
> [Reference{ResourceKey[minecraft:worldgen/biome / minecraft:meadow]=net.minecraft.world.level.biome.Biome@70f01a04}, Reference{ResourceKey[minecraft:worldgen/biome / terralith:cave/mantle_caves]=net.minecraft.world.level.biome.Biome@1dadab94}]

### Additional context

I've created a small private modpack with 39 mods installed.
All the following mods I use, uses their latest version.
-Additional Structures
-Amplified Nether
-Bee Fix
-Biomes O' Plenty
-Bountiful (Forge)
-Cave Spelunking[Forge/Fabric]
-ChoiceTheorem's Overhauled Village
-Chunky (Forge)
-Continents
-Cupboard
-DEUF - Duplicate Entity UUID Fix
-Dungeon Crawl
-Dungeons and Taverns
-Durt's Nether Dungeons
-Dynamic View[Forge]
-Explorify - Dungeons & Structures
-Farsight [Forge]
-Fastload
-Galosphere
-Geophilic - Biome Overhauls
-Kambrik
-Kiwi 🥝 (Forge)
-Kotlin for Forge
-MES - Moog's End Structures
-MVS - Moog's Voyager Structures
-Nullscape
-Open Loader (So that I could use Ecospherical Expansion - Lite, a 1.20.1 biome datapack)
-Simply Improved Terrain
-Snow Under Trees
-Snow! Real Magic! ⛄ (Forge)
-Structory
-Structure Essentials[Forge/Fabric]
-Tectonic
-TerraBlender (Forge)
-Terralith
-Twigs
-Wabi-Sabi Structures (Forge)
-When Dungeons Arise - Forge!
-Yeetus Experimentus

[crash-2023-08-11_16.25.27-client.txt](https://github.com/Stardust-Labs-MC/Terralith/files/12322549/crash-2023-08-11_16.25.27-client.txt)
[latest.log](https://github.com/Stardust-Labs-MC/Terralith/files/12322552/latest.log)

**Comment by catter1** [comment]
Thank you, will take a look this weekend.

**Comment by catter1** [comment]
Apologies for the delay on this - moving the conversation to Dekunutter/eastwardjourneys#3 so I can communicate with their dev.

**Comment by catter1** [comment]
Fixed in 2.4.4

**Comment by SupGamerNL** [comment]
My game still crashes on the Feature order cycle.
In my opinion it might even be a bug with the datapack that I use: "Ecospherical Expansion - Lite".

I have attached both the .log and the crash...-server.txt
[crash-2023-08-30_11.42.10-server.txt](https://github.com/Stardust-Labs-MC/Terralith/files/12474273/crash-2023-08-30_11.42.10-server.txt)
[latest.log](https://github.com/Stardust-Labs-MC/Terralith/files/12474275/latest.log)

I am using the latest version of Terralith 2.4.5 and all other mods in my private pack are updated to their latest version.

**Comment by catter1** [comment]
@SupGamerNL That is a different mod, and therefore a different issue. Created #45, we'll move there.
